// ConfigKey.h
#pragma once

using namespace std;

enum class ConfigKey {
    // === CARD ===
    CARD_DAMAGE_NORMAL,
    CARD_DAMAGE_PIERCE,
    CARD_DAMAGE_STUN,
    CARD_SHIELD_GAIN,
    CARD_DAMAGE_REDUCTION_RATIO,
    CARD_DODGE_CHANCE,
    CARD_RAGE_GAIN,

    // === DECK ===
    DECK_INITIAL_SIZE,
    DECK_MIN_SIZE,

    // === PLAYER ===
    PLAYER_MAX_HP,
    PLAYER_MAX_RAGE,
    PLAYER_CURSED_ENERGY_PER_TURN,

    ATTACK_ENERGY_DAMAGE_SCALE,
    DEFENSE_ENERGY_DAMAGE_REDUCTION_SCALE,

    CRIT_CHANCE,
    CRIT_DAMAGE_MULTIPLIER,

    // === JACKPOT ===
    JACKPOT_CHANCE,
    JACKPOT_DURATION_TURNS,
    JACKPOT_BLOCK_TURNS
};
